
import { Badge, BadgeId, QuizHistoryItem, Difficulty } from './types';
import { TrophyIcon } from './components/icons/TrophyIcon';
import { StarIcon } from './components/icons/StarIcon';
import { BrainIcon } from './components/icons/BrainIcon';
import { CalendarIcon } from './components/icons/CalendarIcon';
import { ChartTrendingUpIcon } from './components/icons/ChartTrendingUpIcon';
import { RocketIcon } from './components/icons/RocketIcon';
import { SparklesIcon } from './components/icons/SparklesIcon';

export const ALL_BADGES: Badge[] = [
    // Mastery & Progress
    {
        id: BadgeId.FirstStep, name: 'First Step', description: 'Complete your first quiz from a PDF document.',
        icon: BrainIcon,
        criteria: (quiz, history) => {
            // Awarded for the user's very first PDF-based quiz.
            if (quiz.source !== 'pdf') {
                return false;
            }
            return history.filter(h => h.source === 'pdf').length === 1;
        },
    },
    {
        id: BadgeId.TopicScholar, name: 'Topic Scholar', description: 'Score 90% or higher on a quiz.',
        icon: BrainIcon,
        criteria: (quiz) => quiz.score / quiz.totalQuestions >= 0.9,
    },
    {
        id: BadgeId.Perfectionist, name: 'Perfectionist', description: 'Get a perfect 100% score on any quiz.',
        icon: TrophyIcon,
        criteria: (quiz) => quiz.score === quiz.totalQuestions,
    },
    {
        id: BadgeId.ExpertExplorer, name: 'Expert Explorer', description: "Pass an 'Advanced' difficulty quiz with a score of 80% or higher.",
        icon: TrophyIcon,
        criteria: (quiz) => quiz.difficulty === Difficulty.Advanced && quiz.score / quiz.totalQuestions >= 0.8,
    },

    // Consistency & Habit
    {
        id: BadgeId.DailyDedication, name: 'Daily Dedication', description: 'Complete a quiz on three consecutive days.',
        icon: CalendarIcon,
        criteria: (quiz, history) => {
            if (history.length < 3) return false;
            const dates = history.slice(0, 3).map(h => new Date(h.date).setHours(0,0,0,0));
            const uniqueDates = [...new Set(dates)];
            if (uniqueDates.length < 3) return false;
            const today = uniqueDates[0];
            const yesterday = new Date(today);
            yesterday.setDate(yesterday.getDate() - 1);
            const dayBefore = new Date(today);
            dayBefore.setDate(dayBefore.getDate() - 2);
            return uniqueDates[1] === yesterday.getTime() && uniqueDates[2] === dayBefore.getTime();
        },
    },
    {
        id: BadgeId.StreakStar, name: 'Streak Star', description: 'Pass 5 quizzes in a row with a score of 80% or higher.',
        icon: ChartTrendingUpIcon,
        criteria: (quiz, history) => {
            if (history.length < 5) return false;
            return history.slice(0, 5).every(h => h.score / h.totalQuestions >= 0.8);
        },
    },
    {
        id: BadgeId.WeekendWarrior, name: 'Weekend Warrior', description: 'Complete a quiz on a Saturday or Sunday.',
        icon: CalendarIcon,
        criteria: (quiz) => {
            const day = new Date(quiz.date).getDay();
            return day === 0 || day === 6; // Sunday or Saturday
        },
    },
    {
        id: BadgeId.QuizWhizBronze, name: 'Quiz Whiz (Bronze)', description: 'Complete 10 quizzes.',
        icon: StarIcon,
        criteria: (quiz, history) => history.length >= 10,
    },
    {
        id: BadgeId.QuizWhizSilver, name: 'Quiz Whiz (Silver)', description: 'Complete 25 quizzes.',
        icon: StarIcon,
        criteria: (quiz, history) => history.length >= 25,
    },
    {
        id: BadgeId.QuizWhizGold, name: 'Quiz Whiz (Gold)', description: 'Complete 50 quizzes.',
        icon: StarIcon,
        criteria: (quiz, history) => history.length >= 50,
    },

    // Performance & Skill
    {
        id: BadgeId.RapidResponder, name: 'Rapid Responder', description: 'Pass a quiz with 10+ questions in under 3 minutes.',
        icon: RocketIcon,
        criteria: (quiz) => quiz.totalQuestions >= 10 && quiz.timeTaken < 180 && quiz.score / quiz.totalQuestions >= 0.8,
    },
    {
        id: BadgeId.AIChallenger, name: 'AI Challenger', description: 'Get a perfect score on a quiz generated by the Chat Agent.',
        icon: SparklesIcon,
        criteria: (quiz) => quiz.source === 'agent' && quiz.score === quiz.totalQuestions,
    },
    {
        id: BadgeId.ComebackKid, name: 'Comeback Kid', description: 'Improve your score on the same topic by at least 30%.',
        icon: ChartTrendingUpIcon,
        criteria: (quiz, history) => {
            const previousAttempts = history.slice(1).filter(h => h.fileName === quiz.fileName);
            if (previousAttempts.length === 0) return false;
            const bestPreviousScore = Math.max(...previousAttempts.map(p => p.score / p.totalQuestions));
            const currentScore = quiz.score / quiz.totalQuestions;
            return currentScore - bestPreviousScore >= 0.3;
        },
    },
    
    // Exploration & Curiosity
    {
        id: BadgeId.Polymath, name: 'Polymath', description: 'Complete quizzes on 5 different topics/files.',
        icon: BrainIcon,
        criteria: (quiz, history) => {
            const uniqueTopics = new Set(history.map(h => h.fileName));
            return uniqueTopics.size >= 5;
        },
    },
    {
        id: BadgeId.FormatSpecialist, name: 'Format Specialist', description: 'Use all three question type preferences.',
        icon: SparklesIcon,
        criteria: (quiz, history, prefs) => prefs?.usedQuestionPreferences?.size === 3,
    },
    {
        id: BadgeId.AgentInteractor, name: 'Agent Interactor', description: 'Complete your first quiz using the Chat Agent.',
        icon: SparklesIcon,
        criteria: (quiz, history) => {
            // Awarded for the user's very first agent-based quiz.
            if (quiz.source !== 'agent') {
                return false;
            }
            return history.filter(h => h.source === 'agent').length === 1;
        },
    },
];

export const checkAndAwardBadges = (
    lastQuiz: QuizHistoryItem, 
    history: QuizHistoryItem[], 
    currentlyEarned: Set<BadgeId>,
    preferences?: any,
): { newBadges: BadgeId[], updatedBadgeSet: Set<BadgeId> } => {
    
    const newBadges: BadgeId[] = [];
    const updatedBadgeSet = new Set(currentlyEarned);

    for (const badge of ALL_BADGES) {
        if (!updatedBadgeSet.has(badge.id)) {
            if (badge.criteria(lastQuiz, history, preferences)) {
                newBadges.push(badge.id);
                updatedBadgeSet.add(badge.id);
            }
        }
    }
    
    return { newBadges, updatedBadgeSet };
};
